apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service-registry-deployment
  namespace: dev
  labels:
    app: api-service-registry
spec:
  replicas: 1  # Number of desired replicas
  selector:
    matchLabels:
      app: api-service-registry
  template:
    metadata:
      labels:
        app: api-service-registry
    spec:
      containers:
        - name: api-service-registry
          image: mahesh541/api-service-registry:latest
          ports:
            - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: api-service-registry-service
  namespace: dev
spec:
  selector:
    app: api-service-registry
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30001  # External port
  type: LoadBalancer
