apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: api-service-registry-deployment
  namespace: dev
  labels:
    app: api-service-registry
spec:
  serviceName: "api-service-registry"
  replicas: 1  # Number of desired replicas
  selector:
    matchLabels:
      app: api-service-registry
  template:
    metadata:
      labels:
        app: api-service-registry
    spec:
      containers:
        - name: api-service-registry
          image: mahesh541/api-service-registry:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: api-service-registry-service
  namespace: dev
spec:
  selector:
    app: api-service-registry
  ports:
    - port: 80
      targetPort: 8081
  type: NodePort