apiVersion: v1
kind: Service
metadata:
  name: eureka
  namespace: dev
spec:
  selector:
    app: eureka-server
  ports:
    - port: 8761
      targetPort: 8081
      protocol: TCP
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka-server
          image: mahesh541/api-service-registry:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
