apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service-registry-deployment
  namespace: dev
  labels:
    app: visitormgmt
spec:
  replicas: 1  # Number of desired replicas
  selector:
    matchLabels:
      app: api-service-registry
  template:
    metadata:
      labels:
        app: api-service-registry
    spec:
      containers:
        - name: api-service-registry
          image: mahesh541/api-service-registry:latest
          ports:
            - containerPort: 8085
