server:
  port: 8081

eureka:
  instance:
    hostname: "${HOSTNAME}.eureka"
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://api-service-registry-deployment-0.api-service-registry-service.default.svc.cluster.local:8081/eureka